# Classifications Enterprise Package
# Advanced enterprise-grade classification system with three-level architecture:
# Version 1: Manual & Rule-Based
# Version 2: ML-Driven Classification  
# Version 3: AI-Intelligent Classification

__version__ = "1.0.0"
__author__ = "Enterprise Data Governance Team"
__description__ = "Advanced three-level classification system surpassing Databricks and Microsoft Purview"

from .models.classification_models import (
    ClassificationRule, ClassificationDictionary, ClassificationAudit, 
    ClassificationResult, SensitivityLabelEnum
)

from .models.ml_models import (
    MLModel, MLTrainingJob, MLPrediction, MLFeedback, MLModelVersion,
    MLModelType, MLModelStatus, TrainingJobStatus, PredictionConfidenceLevel, FeedbackType
)

from .models.ai_models import (
    AIModel, IntelligentAssistantSession, AssistantInteraction, AIInsight,
    DomainIntelligence, ContextAwareSearch, AutoGeneratedTag,
    AIOptimizationRecommendation, ExplainableAITrace,
    AIModelType, IntelligenceLevel, InsightType, RecommendationPriority
)

from .services.classification_service import ClassificationService
from .services.ml_service import MLClassificationService
from .services.ai_service import AIIntelligentClassificationService

from .api.routes.classification_routes import router as classification_router
from .api.routes.ml_routes import router as ml_router
from .api.routes.ai_routes import router as ai_router

__all__ = [
    # Models
    "ClassificationRule", "ClassificationDictionary", "ClassificationAudit", 
    "ClassificationResult", "SensitivityLabelEnum",
    "MLModel", "MLTrainingJob", "MLPrediction", "MLFeedback", "MLModelVersion",
    "MLModelType", "MLModelStatus", "TrainingJobStatus", "PredictionConfidenceLevel", "FeedbackType",
    "AIModel", "IntelligentAssistantSession", "AssistantInteraction", "AIInsight",
    "DomainIntelligence", "ContextAwareSearch", "AutoGeneratedTag",
    "AIOptimizationRecommendation", "ExplainableAITrace",
    "AIModelType", "IntelligenceLevel", "InsightType", "RecommendationPriority",
    
    # Services
    "ClassificationService", "MLClassificationService", "AIIntelligentClassificationService",
    
    # Routes
    "classification_router", "ml_router", "ai_router",
    
    # Package info
    "__version__", "__author__", "__description__"
]