### === backend/app/services/lineage.py ===
from pyapacheatlas.core import PurviewClient, AtlasEntity, AtlasProcess
from app.core.config import settings
from app.core.security import get_auth
import uuid


def create_lineage_process(payload: dict):
    source_qn = payload.get("sourceQualifiedName")
    target_qn = payload.get("targetQualifiedName")
    process_name = payload.get("processName", "lineage-process")

    process_qn = f"{process_name}_{uuid.uuid4()}"

    process = AtlasProcess(
        name=process_name,
        typeName="Process",
        qualifiedName=process_qn,
        inputs=[{"qualifiedName": source_qn, "typeName": "azure_sql_table"}],
        outputs=[{"qualifiedName": target_qn, "typeName": "azure_sql_table"}],
        attributes={
            "description": "Lineage generated by PurSight",
        }
    )

    client = PurviewClient(
        account_name=settings.PURVIEW_NAME,
        authentication=get_auth()
    )

    result = client.upload_entities(batch=[process])
    return {"lineage_upload_result": result}
